name: aws_tgw_start_stop_fw
# label used for menu selection
label: AWS Transit Gateway Firewalls Step 3 Route Failover Demo

description: >

  A lambda function monitors the health of the firewalls and will failover connections to the standby firewall.
  Various configuration options are available to modify the behaviour of the failover script.

  1) Splitroutes yes enables Internet traffic via primary firewall (FW1) with East/West by the secondary (FW2)

  3) Preempt YES/NO controls the failback option once the failed device becomes available again


# type of skillet (panos or panorama or template or terraform)
type: python3

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: AWS Transit Gateway Direct Attached Firewalls

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: firewall
    description: Select Firewall
    dd_list:
      - key: "Firewall 2"
        value: "Firewall2"
      - key: "Firewall 1"
        value: "Firewall1"
    type_hint: dropdown
  - name: action
    description: Start or Stop Firewall
    type_hint: dropdown
    dd_list:
      - key: "Start"
        value: "start"
      - key: "Stop"
        value: "stop"
  - name: split_routes
    description: Split East/West vs Oubound connections
    type_hint: dropdown
    dd_list:
      - key: "Yes"
        value: "yes"
      - key: "No"
        value: "no"
  - name: preempt
    description: Preempt (Failback when device is available)
    type_hint: dropdown
    dd_list:
      - key: "Yes"
        value: "yes"
      - key: "No"
        value: "no"
  - name: aws_access_key
    description: AWS Access Key
    default: abc123
    type_hint: text
  - name: aws_secret_key
    description: AWS Secret Key
    default:
    type_hint: password

# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: script
    file: ../../start-stop-fw.py
